services:
  # Docker container run configuration for front end
  client:
    build: ./client
    image: fool-proof-client:latest
    container_name: fool-proof-client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_API: ${NEXT_PUBLIC_BACKEND_API}
    develop:
      watch:
        # sync when file in host file changes except for files in ignore.
        - action: sync
          path: ./client
          target: /fool-proof
          ignore: 
            - node_modules/
            - .next/
        # rebuild when dependencies change
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/pnpm-lock.json
        # sync and then restart when configs change
        - action: sync+restart
          path: ./client/next.config.json
          target: /fool-proof/next.config.json
        - action: sync+restart
          path: ./client/postcss.config.mjs
          target: /fool-proof/postcss.config.mjs
        - action: sync+restart
          path: ./client/tailwind.config.ts
          target: /fool-proof/tailwind.config.ts
        - action: sync+restart
          path: ./client/tsconfig.json
          target: /fool-proof/tsconfig.json
        - action: sync+restart
          path: ./client/components.json
          target: /fool-proof/components.json
  # Docker container run configuration for backend
  server:
    build: ./server
    image: fool-proof-server:latest
    container_name: fool-proof-server
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_FRONTEND_URL: ${SPRING_FRONTEND_URL}
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET} 
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /server/src
        - action: rebuild
          path: ./server/build.gradle
  # Docker container run configuration for mysql database
  database:
    image: mysql:8.0
    container_name: fool-proof-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
  # Docker container run configuration for redis database
  redis:
    image: redis:6.2
    container_name: fool-proof-rdb
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    

          

