services:
  # Docker container run configuration for front end
  client:
    build: ./client
    image: fool-proof-client:latest
    container_name: fool-proof-client
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./client
          target: /fool-proof
          action: sync
        - path: ./client/package.json
          action: rebuild
        - path: ./client/pnpm-lock.json
          action: rebuild
  # Docker container run configuration for backend
  server:
    build: ./server
    image: fool-proof-server:latest
    container_name: fool-proof-server
    develop:
      watch:
        - path: ./server
          target: /fool-proof
          action: sync
